version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - shop-network
  backend:
    image: diplom-project
    ports:
      - '8080:8080'
    environment:
      SHOP_DB_USER: ${DATABASE_USER}
      SHOP_DB_PASSWORD: ${DATABASE_PASSWORD}
      SHOP_DB_NAME: ${DATABASE_NAME}
      SHOP_DB_HOST: database:5432
    depends_on:
      - database
    networks:
      - shop-network
networks:
  shop-network:
    driver: bridge