spring:
  application:
    name: diplom-project
  datasource:
    url: jdbc:postgresql://${SHOP_DB_HOST}/${SHOP_DB_NAME}
    username: ${SHOP_BD_USER}
    password: ${SHOP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: liquibase/changelog-master.xml
app:
  jwt:
    expirationMs: 604800000
    secret: defaultdefaultdefaultdefaultdefaultdefault
